### ISSUE TITLE
Suppressions manquantes dans la table  grr_j_user_room.

### ISSUE THREAD

**Issue by plegay** [GIP-RECIA/ESCOSynchroGRR#4]
Bonjour,
Lors de suppressions d'un utilisateurs dans GRR (aprés le délai de rigueur) il reste des références à cet utilisateur dans la table grr_j_user_room.

Cordialement

**Comment by GFI-ORLEANS** [comment]
Problème identifié, 
La relation n’est pas présente dans le mapping hibernate. 
Je corrige dans la foulée
