### ISSUE TITLE
Data truncation: Data too long for column 'name' 

### ISSUE THREAD

**Issue by plegay** [GIP-RECIA/ESCOSynchroGRR#5]
Je viens de tester le dernier commit en mettant une date ancienne pour mettre à jour tout les comptes.

J'ai l'erreur suivante :
  `
2019-05-07 16:47:05 [INFO ] Ecriture en base GrrEtablissement : 0450066C
2019-05-07 16:47:05 [ERROR] Data truncation: Data too long for column 'name' at row 1
2019-05-07 16:47:05 [INFO ] Debut Process pour l'établissement : 0450066C
2019-05-07 16:47:05 [INFO ] Mise a jour de l'établissement ID : 5
2019-05-07 16:47:05 [ERROR] Encountered an error executing step misAjourEtablissement in job Syncro
org.springframework.retry.ExhaustedRetryException: Retry exhausted after last attempt in recovery path, but exception is not skippable.; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement

`
Le nom de l'établissement est:
LP LYC METIER-MAL LECLERC DE HAUTECLOCQUE-ac-ORL._TOURS

je joins le log pour la trace complète de l'erreur
[system.log](https://github.com/GIP-RECIA/ESCOSynchroGRR/files/3153242/system.log)

**Comment by GFI-ORLEANS** [comment]
![idea64_2019-05-09_10-07-20](https://user-images.githubusercontent.com/29436029/57437587-5fab9880-7242-11e9-87d0-23534c12e396.png)

La colonne name de grr_etablissement est en varchar(50)

Nous devons tronquer le nom pour le mettre en base.

**Comment by plegay** [comment]
L'ancienne applie devait effectivement tronquer (ou la version de mysql??) , le short name aussi est tronqué.
Il faut donc faire pareille.

**Comment by plegay** [comment]
C'est passé pour cet établissement , mais j'ai une nouvelle erreur. 
J'ouvre une nouvelle issue
