### ISSUE TITLE
Column 'code_etablissement_principal' cannot be null

### ISSUE THREAD

**Issue by plegay** [GIP-RECIA/ESCOSynchroGRR#6]
Toujours sur une mise a jour de tous les comptes :

J'ai l'erreur suivante :
`
2019-05-09 11:43:54 [INFO ] Debut du Writer MisAjourEtablissement
2019-05-09 11:43:54 [INFO ] Ecriture en base GrrEtablissement : 0180007K
2019-05-09 11:43:54 [ERROR] Column 'code_etablissement_principal' cannot be null
2019-05-09 11:43:54 [INFO ] Debut Process pour l'établissement : 0180007K
2019-05-09 11:43:54 [INFO ] Mise a jour de l'établissement ID : 7
2019-05-09 11:43:54 [ERROR] Encountered an error executing step misAjourEtablissement in job Syncro
org.springframework.retry.ExhaustedRetryException: Retry exhausted after last attempt in recovery path, but exception is not skippable.; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.springframework.batch.core.step.item.FaultTolerantChunkProcessor$5.recover(FaultTolerantChunkProcessor.java:413)

`
Dans ldap j'ai bien ENTStructureUAI de renseigné ainsi que le SIREN ??
Ci-joint le log complet:
[system.log](https://github.com/GIP-RECIA/ESCOSynchroGRR/files/3161468/system.log)

**Comment by plegay** [comment]
Je precise que dans un premier temps j'avais oublié de déclarer les regroupement d'établissement.
Aprés l'avoir fait j'ai la même erreur.

Le contenu de la table grr_etablissement_regroupement:

`
select * from grr_etablissement_regroupement;

code_etablissement_secondaire | code_etablissement_principal 
0410860M                      | 0410001D                     
0180026F                      | 0180024D                     
0180042Y                      | 0180007K                     
0280957N                      | 0280015P                     
`

**Comment by GFI-ORLEANS** [comment]
Le problème vient des contraintes NOT NULL sur la table grr_etablissement_regroupement.
Hibernate veut passer la valeur à NULL pour ensuite la supprimer ce qui ne peut marcher (refus de mysql) 
J'ai passé ce fonctionnent en requête native pour outrepasser cette contrainte.

**Comment by plegay** [comment]
Ok c'est passer 
Merci
